name: Build and push to jfrog artifactory
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v2
    - name: build, cache & export
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: morya994.jfrog.io/docker/lendbuzz_ex:${{github.sha}}
        outputs: type=docker,dest=/tmp/lendbuzz_ex.tar
        cache-from: type=registry,ref=user/app:latest
        cache-to: type=inline
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: lendbuzz_ex_image
        path: /tmp/lendbuzz_ex.tar
        
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: lendbuzz_ex_image
        path: /tmp
    - name: load image from artifact
      run: |
        docker load --input /tmp/lendbuzz_ex.tar
    - name: login to jfrog artifactory
      uses: docker/login-action@v2.1.0
      with:
        registry: morya994.jfrog.io/docker/
        username: ${{secrets.JFROG_USERNAME}} 
        password: ${{secrets.JFROG_PASS}}
    - name: docker push
      run: docker push morya994.jfrog.io/docker/lendbuzz_ex:${{github.sha}}
    
