name: Build and push to jfrog artifactory
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/cache
        key: app-cache
    - name: docker build
      run: docker build . --tag morya994.jfrog.io/docker/lendbuzz_ex:${{github.sha}}
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: myimage
        path: /tmp/myimage.tar
        
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: myimage
        path: /tmp
    - name: load image from artifact
      run: |
        docker load --input /tmp/myimage.tar
    - name: login to jfrog artifactory
      uses: docker/login-action@v2.1.0
      with:
        registry: morya994.jfrog.io/docker/
        username: ${{secrets.JFROG_USERNAME}} 
        password: ${{secrets.JFROG_PASS}}
    - name: docker push
      run: docker push morya994.jfrog.io/docker/lendbuzz_ex:${{github.sha}}
    
