name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/cache
        key: app-cache
    - name: Build the Docker image
      run: docker build . --tag morya994.jfrog.io/docker/lendbuzz_ex:${{github.sha}}
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: morya994.jfrog.io/docker/
        username: ${{secrets.JFROG_USERNAME}} 
        password: ${{secrets.JFROG_PASS}}
    - name: Push the Docker image
      run: docker push morya994.jfrog.io/docker/lendbuzz_ex:${{github.sha}}
